apiVersion: v1
kind: CoworkingConfigMap
metadata:
  name: db-env
data:
  DB_NAME: "coworkdb"
  DB_USER: "coworker"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  POSTGRES_PASSWORD: "TTNhczNhc0EzM2Fp"